sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: JAbSJgbN1dws/Ls0b474QMMBKxYRRCH1o1f8L6lQwfJ/K5vooLfGe4hFuJGS90KrEfE2igIEzkbUpUgb7ylnRayIoX5aTGR6Fui7OjJ2pVHEIICP93u/okyjc6jnubXZO1BhiQZXk9I4lktyO5msxxF0FSSn7uXCyLzRh9S33TiXSy6F0THnTEnmJlGTWIC3uS4IOGaIF9qPuHT9e7Qo7Q4PQLRhXcelUGCO/xjT+cCY0/jcL12TdaM0IZqEu634x1nvKsGLNGEWzSJPeVSwO5B/trR5EMPg8aGADj5V9Tq6zNGUMqlIal0ZrbtRDUAWTNcWw6yQ1yz9NMELc3Xg1OoJX0zTvVALFLKT+pLC2ILtNRJOM/SX9UvvwYrcv4LFaV+WLkgzEZ1azJuU1k+1N7RWZ7j+8IlJ+wwbzlA4Y6eLM1l0ohVPNbQVI9xlarGRvmOezPV//ppUEjus7KS+48S+WEPyxuJ8g3+HAl2luyZr2Ha4zOm4DZZxRFpINkR9i9OZbHmA2ixHhRDxP3koetrfVKBgBWVzd94GwBjU5JZw3CR7/ww789LMm/4wr2ksRyIDVOBnAVdYi2R6uLRuilWatGvoeZqvUinT2DUsMmxRjD416NJXwqjq/QBf2AsDV8AcBbyA3tzjpxGgRRJ8IOPi3YD3q+Q6G3Jtp8tUiNw=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: vbIwliT/q88U/j0ypi47EjmK5O+z6ceUmjVWbKYSPfnEtXdGki9EdpglVdXKRNxv63BvQmcE6ZoPtakABunfyU12YyhuhPpxngkJcU7knv7WhFZFq3woSqB6IhMlsSzIut+zfA5JcNR5Skt7Opu57M8MItQpG91Z3GB5BHQOQHyeAGxgVc/Nj0oZpdOF7B0PmNxIImshT5ZAmnja7lc+tb8d4/Qy/NPM20K65epfaMKRQ1mViC1/auPWGo2sy3taUfvdw3I3m2VoMnROEToKp+s4jkhZyqKGpk29oO+fZypkmjrst8iSs27Fy1m2Lbw0DGBUoc7UY/RQ6/8lGKrYzDhfd6dzNDUAaELwg7DYNSPzyNUQxfNwHL+sPuPkbsq6jJJvzZHO53oNijt0MV5YPsVG95c31pfCGxRVGrgjORkEewzgyrNuHACUhgs8gXyS2bT4gLXQ2O3fdJPY2jJBNwsLcr1h1HAMr2aqYY1yPymy3zuC9jPuk6PwNqXGdvFI+pSwj95BP/3kELPahWZxiX2ZxDFZFh/WTFk+h2sUM9G+8pXzrh1DFwt76/Wi1L5ZjOUNby3t2EDv5XqoIf2+shNdLSjvwgUQU3ZCXPf3dHo9Msm9DdzPWR4/Yby4I0lLSMjnGE2qLiDqO+RXjTowzUpG7tUyRCt5r6tOQ4iwUs0=
